baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rob's Blah Blog"
theme = "indigo"
paginate = 3

[params]
  Author = "Rob Miller"
  # Subtitle = "A subtitle for your site"

  # Contact/social-network identifiers for social icons
  EmailAddress = "rdmagm062699@gmail.com"
  GitHubUser = "rdmagm062699"
  LinkedInUser = "rob-miller-9a85762"
  TwitterUser = "rdmatwork"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "rdmagm062699@gmail.com"
    GitHubUser = "rdmagm062699"
    TwitterUser = "rdmatwork"
    Country = "USA"
    City = "Papillion"